// https://rencore.com/blog/building-sharepoint-framework-client-side-web-parts-angular
// CREATING THE ANGULAR APPLICATION
import * as angular from 'angular';
import { Version } from '@microsoft/sp-core-library';
import {
  BaseClientSideWebPart,
  IPropertyPaneConfiguration,
  PropertyPaneTextField
} from '@microsoft/sp-webpart-base';
import { escape } from '@microsoft/sp-lodash-subset';

import styles from './Weather.module.scss';
import * as strings from 'weatherStrings';
import { IWeatherWebPartProps } from './IWeatherWebPartProps';
import {WeatherService} from './app/WeatherService';
import {WeatherPropService} from './app/WeatherPropService';
import {WeatherController} from './app/WeatherController';
declare function require(path: string) : string;
var viewHtml = require("./templates/WeatherView.template.html");

export default class WeatherWebPart extends BaseClientSideWebPart<IWeatherWebPartProps> {

  public render(): void {
    
      // The first time, set up the Angular app
      if(!this.renderedOnce) {

          // Adjust CSS classes to unique class names for this WP
          this.domElement.innerHTML = this.fixCss(viewHtml);

          // Configure the Angular app
          angular.module('weatherWidget', [])
              .service('WeatherPropService', WeatherPropService)
              .service('WeatherService', WeatherService)
              .constant ('appId', 'ecb1f756686518281c429bf5b7498d70')
              .controller('WeatherController', WeatherController);

          // Run the angular app
          angular.bootstrap(this.domElement, ['weatherWidget']);

      }

      // Every time we render, update the web part properties
      var service : any = 
        angular.element(this.domElement).injector().get('WeatherPropService');
      service.UpdateProperties(this.properties);

    // this.domElement.innerHTML = `
    //   <div class="${styles.helloWorld}">
    //     <div class="${styles.container}">
    //       <div class="ms-Grid-row ms-bgColor-themeDark ms-fontColor-white ${styles.row}">
    //         <div class="ms-Grid-col ms-u-lg10 ms-u-xl8 ms-u-xlPush2 ms-u-lgPush1">
    //           <span class="ms-font-xl ms-fontColor-white">Welcome to SharePoint!</span>
    //           <p class="ms-font-l ms-fontColor-white">Customize SharePoint experiences using Web Parts.</p>
    //           <p class="ms-font-l ms-fontColor-white">${escape(this.properties.description)}</p>
    //           <a href="https://aka.ms/spfx" class="${styles.button}">
    //             <span class="${styles.label}">Learn more</span>
    //           </a>
    //         </div>
    //       </div>
    //     </div>
    //   </div>`;
  
  }

  // Function to fix the dynamic CSS classes generated by SPFx
  // NOTE: You must list all class names here, this is a brittle
  //       hack! Looking for a better approach when using HTML templates.
  //       SPFx generates a const which can't be enumerated at runtime.
  private fixCss(html: string) : string {

    // Instantiate the styles collection
    var classTable = styles;

    var viewHtml: string = html;

    for (let c in classTable) {
      viewHtml = viewHtml.replace('class="' + c + '"',
                                  'class="' + classTable[c] + '"');
    }

    return viewHtml;
    }


  protected get dataVersion(): Version {
    return Version.parse('1.0');
  }


  protected getPropertyPaneConfiguration(): IPropertyPaneConfiguration {
    return {
      pages: [
        {
          header: {
            description: strings.PropertyPaneDescription
          },
          groups: [
            {
              groupName: strings.BasicGroupName,
              groupFields: [
                PropertyPaneTextField('location', {
                  label: strings.LocationFieldLabel
                })
              ]
            }
          ]
        }
      ]
    };
  }
}
